### ISSUE TITLE
times are incorrect for e-mail events

### ISSUE THREAD

**Issue by dan-ding** [chuckdrew/mailgun_magento#2]
I haven't investigated far enough to see if it's related to the events timestamp column being a varchar (when it should be a ... timestamp?).

Dates show up incorrectly as well - E.g. whatever is stored for July 6th 2015 shows as June 7th 2015, and so on.

**Comment by chuckdrew** [comment]
Thanks for letting me know. I will take a look...

Chuck

**Comment by dan-ding** [comment]
pull request at: https://github.com/chuckdrew/mailgun_magento/pull/3

**Comment by dan-ding** [comment]
Seems good now. Thanks Chuck!
